### ISSUE TITLE
Lag management, client-side lag?

### ISSUE THREAD

**Issue by Aralun** [Kriegslustig/meteor-simulatency#1]
As of today the outgoing traffic is being delayed, not the incoming one.

Should this incoming traffic be delayed on the client, or on the server?

**Comment by halbgut** [comment]
Yeah, good point! I thought about that. I guess the easiest way to do it is on the server. I'll add that real quick shouldn't be to hard.

**Comment by halbgut** [comment]
[That](https://github.com/Kriegslustig/meteor-simulatency/commit/61a982dd82fcd6c67d4bd65c548b5afbd66170df) should do it
